Connected buttons to new retirement flow and loading spinner
KlimaDAO/klimadao pull request #1188
Opened 2023-06-07 15:05 UTC by psparacino

## Description

Wired up buttons to new retirement flow and used next/link where previously omitted.

Fixed a `<p>` nesting error in the CustomizableModal to allow for formatted titles w/o nesting error

Included a spinner for while web3 is initializing. With the new wire-ups and using Link it was difficult to find a case where this spinner actually showed.

## Related Ticket

Resolves #1174 

## Checklist

- [X] I have run `npm run build-all` without errors
- [X] I have formatted JS and TS files with `npm run format-all`

2023-06-07 19:45 UTC, Atmosfearful requested changes

2023-06-07 21:38 UTC, psparacino commented on carbonmark/components/pages/Portfolio/AssetProject/index.tsx
> +          <ButtonPrimary
it doesn't look like anything will collide in the ButtonBase(?). As long as there is no navigation or preventDefault or actions of that nature in there, it should be fine. I used renderLink for all of these and it seems to work really well.

2023-06-08 13:09 UTC, jabby09 requested changes
@psparacino @Atmosfearful @0xMakka I found more issues this morning.

(1) I did a retirement with no beneficiary and the digital receipt is missing the Download PDF button? https://carbonmark-git-tufnel-wire-up-retirement-flow-and-1174-klimadao.vercel.app/retirements/0x6476edf98bdc5ee62f9d4e4bf8932d69ed685483/15

(2) When the retirement receipt first loads, I cannot scroll, not sure if this image helps show that but to scroll the page I have to refresh my browser first.
<img width="1436" alt="Screenshot 2023-06-08 at 9 58 58 AM" src="https://github.com/KlimaDAO/klimadao/assets/103535195/51043b98-09bf-48d0-be98-b7872a67d0ec">

(3) Not necessarily a blocker but we have design/implementation drift on these confirm modals. Different sizes, different buttons, with and without scroll bars. I can work with professor to review all this and come up with design standards but wanted to mention it here.

<img width="558" alt="Screenshot 2023-06-08 at 9 56 40 AM" src="https://github.com/KlimaDAO/klimadao/assets/103535195/49571f72-c3fb-4a45-b372-34740b52771a">

<img width="515" alt="Screenshot 2023-06-08 at 9 57 55 AM" src="https://github.com/KlimaDAO/klimadao/assets/103535195/72aede9b-1082-41fe-8ef3-f78f68957092">

2023-06-08 13:53 UTC, psparacino commented
I'll leave the first two items for 0xMakka but yes I noticed the requirement for a beneficiary name in order to show/download the PDF when I was testing

Re: modal standardizing, the top one looks like it's from the first iteration of the retirement flow that used the pre-existing Modal component (that shouldn't be in the current retire flow? if it is, where is it?). The reviews were that it was too far off the design so I created a modal that was more customizable to fit the design (https://www.figma.com/file/I5hXFeW1DKjV7agHq7T4UZ/Portfolio?type=design&node-id=247-10947&t=O8YxVEdk72TWMjKx-0), which is the second image. Open to whatever works, but as far as I can tell the top image isn't in the current implementation(?).

2023-06-08 14:04 UTC, jabby09 commented
@psparacino the top image was from the `retire from pool listing` that @ladytrekker just implemented https://github.com/KlimaDAO/klimadao/issues/1189

2023-06-08 18:21 UTC, 0xMakka commented
@jabby09 I've opened up a PR with a fix for item [1]. In this case I wasn't showing the button if the beneficiary name was missing, I've now removed this check.

With regards [2] - I've tried reproducing this but can't. Is this happening for every retirement for you, and is there anything you are doing in particular for this to happen or it's just not scrollable immediately when you load the page?

2023-06-08 19:23 UTC, jabby09 commented
> With regards [2] - I've tried reproducing this but can't. Is this happening for every retirement for you, and is there anything you are doing in particular for this to happen or it's just not scrollable immediately when you load the page?

@0xMakka @psparacino i discussed this with @Atmosfearful - when I described the situation he seemed to know what is was, something about the modal and not clearing something

2023-06-08 21:13 UTC, Atmosfearful approved these changes

2023-06-08 21:14 UTC, merged