[DRAFT] 0xMakka / #1183 initial implementation of language switcher
KlimaDAO/klimadao pull request #1206
Opened 2023-06-12 22:13 UTC by 0xMakka

## Description

DRAFT - Please don't merge as this is a WIP and incomplete.

## Related Ticket

Resolves #1183 

## Checklist

- [X] I have run `npm run build-all` without errors
- [X] I have formatted JS and TS files with `npm run format-all`

2023-06-13 12:31 UTC, jabby09 approved these changes

2023-06-13 17:30 UTC, jabby09 commented
@0xMakka @Atmosfearful do we agree this is complete enough that the translators can work off the PR link to finish the translation work?

2023-06-14 17:16 UTC, Atmosfearful requested changes
@jabby09 Yes Pseudo is working so we can use this carbonmark preview link to start identifying missing translations. However I'm realizing that it's a bit cumbersome to have a non-dev identify the strings, as theyd have to screenshot them and have a dev go in to tag the manyways.

So it probably would go faster if we just have @0xMakka dig through all the views and slap `<Trans>` or `t` tags on everything he can find. Let's just do that in this PR.

Please note that we can't translate CMS content, so project names and descriptions will be untranslated.

Also for you to note @0xMakka we are not using `ids` anymore except for very long strings. This reduces a ton of boilerplate: so `<Trans>My String</Trans>` and 
```
t`My Message`
```
is all you need to do :)

I'm gonna add a section in our github wiki on translation best practices and update this comment with a link to it...

2023-06-14 17:16 UTC, Atmosfearful commented on carbonmark/components/ChangeLanguageButton/index.tsx
> +  };
This is the approach one would take for a single page app where locales are managed client-side (like our `app` package), but Carbonmark can use nextjs builtins. See `site` for an example:

https://github.com/KlimaDAO/klimadao/blob/9d32d9678e53dea2566fd45ca3b61b4283fc6803/site/components/ChangeLanguageButton/index.tsx#L13

2023-06-14 17:33 UTC, jabby09 commented
> It's hard to see but the bg color doesnt match the button links

nice catch, I did not see that!

2023-06-14 18:02 UTC, 0xMakka commented
> It's hard to see but the bg color doesnt match the button links 
> ![image](https://github.com/KlimaDAO/klimadao/assets/88635679/2b99dcd0-99bc-4c14-a51e-41243a057356)
> 

Thanks for the feedback @Atmosfearful - eagle eye 😎, great catch I didn't notice this either.

And good to know with using the nextjs built ins, will make the changes to this 👍.

2023-06-22 19:05 UTC, Atmosfearful approved these changes

2023-06-29 17:33 UTC, merged