Retire: Show Assets from Portfolio
KlimaDAO/klimadao pull request #1244
Opened 2023-06-28 13:12 UTC by ladytrekker

## Description

This PR renders available assets a carbonmark user owns.
When clicking on an asset, the user is taken to the page "retire from portfolio".
This page is a subpage of the Portfolio page (not of the retire page). 

## Related Ticket

Resolves https://github.com/KlimaDAO/klimadao/issues/1210

## Checklist

- [ ] I have run `npm run build-all` without errors
- [ ] I have formatted JS and TS files with `npm run format-all`

2023-06-28 16:49 UTC, jabby09 requested changes
- ~hide when not connected~ CONFIRMED 
- ~loading spinner when connected~ CONFIRMED
- ~empty state when no assets~ Will confirm and possibly change in future PR
- ~empty state when not a carbonmark user~ CONFIRMED
- ~render assets with project data~ CONFIRMED
- ~link to form~ CONFIRMED

- [x] VCS code is wrapping with long category name
<img width="348" alt="Screenshot 2023-06-28 at 12 46 29 PM" src="https://github.com/KlimaDAO/klimadao/assets/103535195/7d287375-768e-47c9-af2d-8d76da3d9d9a">

- [x] Quantity Available on the card should be Available Tonnes: and the tonnes bolded. See design example below:
![Screenshot 2023-06-28 at 12 52 31 PM](https://github.com/KlimaDAO/klimadao/assets/103535195/ad27fc3d-7fef-4f2a-94b3-4867196dc4d9)

- [x] Professor commented the space between the titles and subtitles is too large in the sections. Can you please double check the padding as per the designs?

2023-06-29 11:03 UTC, ladytrekker commented
@jabby09 

> Quantity Available on the card should be Available Tonnes

I changed it now to "Available Tonnes"

Just to be clear: These are the assets a user owns and are exactly the same what the user sees on the portfolio
=> carbonmark.com/portfolio
On the Portfolio it says "Quantity available" (your amount of assets you own from this project which you can sell/create a listing from or retire) and not tonnes.

2023-06-29 15:15 UTC, Atmosfearful approved these changes

2023-06-30 12:35 UTC, jabby09 commented
> I don't think I need an extra empty state?
> See screenshots above.
> Or let's do this in a follow-up PR. So this one can get merged.

@ladytrekker professor had requested some changes for this empty state but yes can move forward with what we have for now.

2023-06-30 12:36 UTC, jabby09 commented
> Just to be clear: These are the assets a user owns and are exactly the same what the user sees on the portfolio
> => carbonmark.com/portfolio
> On the Portfolio it says "Quantity available" (your amount of assets you own from this project which you can sell/create a listing from or retire) and not tonnes.

@ladytrekker good catch! I was just comparing to the figma design for that page but agree consistency would be better. I've sent this question to professor. If we need to adjust can do it in a new PR.

2023-06-30 12:36 UTC, jabby09 approved these changes

2023-06-30 13:48 UTC, merged