make project cards look like on figma
KlimaDAO/klimadao pull request #1364
Opened 2023-07-24 14:10 UTC by sprrwhwk

## Description

## Related Ticket

Resolves #1336 

## Checklist

- [ ] I have run `npm run build-all` without errors
- [ ] I have formatted JS and TS files with `npm run format-all`

2023-07-25 13:55 UTC, jabby09 requested changes
@sprrwhwk 

Projects cards on marketplace look good to me now and match the figma design.

We also now have project cards on the retire page https://carbonmark-git-fix-project-cards-klimadao.vercel.app/retire

The title and description treatment you have applied to the marketplace cards should also be applied to the cards on the retire page. The other design elements of the cards on the retire page should remain (like the gold border, available tonnes content etc)

2023-07-25 15:34 UTC, sprrwhwk commented
> @sprrwhwk
> 
> Projects cards on marketplace look good to me now and match the figma design.
> 
> We also now have project cards on the retire page https://carbonmark-git-fix-project-cards-klimadao.vercel.app/retire
> 
> The title and description treatment you have applied to the marketplace cards should also be applied to the cards on the retire page. The other design elements of the cards on the retire page should remain (like the gold border, available tonnes content etc)

Done in [2a7af1d](https://github.com/KlimaDAO/klimadao/pull/1364/commits/2a7af1dc045c361d0a55595d2b360300b1d93af7)

2023-07-25 17:39 UTC, jabby09 approved these changes
looks good!

2023-08-02 20:53 UTC, Atmosfearful approved these changes

2023-08-02 20:53 UTC, merged