Emc/feature/carbonmark map view
KlimaDAO/klimadao pull request #1408
Opened 2023-08-09 22:59 UTC by 0xemc

## Description

Speaking with @Atmosfearful recently, we decided that Carbonmark could benefit from a Map View so here it is:

https://github.com/KlimaDAO/klimadao/assets/7104689/6a8d870b-a4a0-4c59-a98e-25d191ef3461

### Remaining:
- [ ] @theprofessora we could benefit from your UI/UX skills to clean this up in the next iteration.
- [ ] Switch to Ubers https://visgl.github.io/react-map-gl/ package so we don't have force reactivity

2023-08-10 12:06 UTC, jabby09 reviewed
ah, very cool!
I won't have time likely until the weekend to look at this in detail, however, note that #1353 will merge very soon and that will add a marketplace control for desktop

<img width="1090" alt="Screenshot 2023-08-10 at 9 05 50 AM" src="https://github.com/KlimaDAO/klimadao/assets/103535195/9c1a7631-a219-4103-aaed-fff1c13451da">

2023-08-10 16:07 UTC, psparacino commented
Super cool(!) and very compelling from a user perspective when buying or retiring

2023-08-10 17:18 UTC, psparacino commented
@0xemc I'm trying to get a local version running to test out some potential tweaks. However I can't seem to get the markers to render. I got the mapbox token from vercel and updated the packages.

In carbonmark-map shows up fine until the getClusters return, which is always an empty array. This.clusterer has 312 points so all the projects look to be loaded.

```
    this.log("bounds", bounds)
    this.log("zoom", Math.floor(zoom))
    this.log("this.clusterer", this.clusterer)
    this.log("this.clusterer.load(compact(this.points))", this.clusterer.load(compact(this.points))) <--- everything looks fine up until this point
    const clusters = this.clusterer.getClusters(bounds, zoom);
    this.log("clusters", clusters) <---- empty
```

Not sure why this.clusterer.getClusters isn't returning the clusters. If you happen to know a potential fix that would be much appreciated, thanks

2023-08-10 22:33 UTC, 0xemc commented
> @0xemc I'm trying to get a local version running to test out some potential tweaks. However I can't seem to get the markers to render. I got the mapbox token from vercel and updated the packages.
> 
> In carbonmark-map shows up fine until the getClusters return, which is always an empty array. This.clusterer has 312 points so all the projects look to be loaded.
> 
> ```
>     this.log("bounds", bounds)
>     this.log("zoom", Math.floor(zoom))
>     this.log("this.clusterer", this.clusterer)
>     this.log("this.clusterer.load(compact(this.points))", this.clusterer.load(compact(this.points))) <--- everything looks fine up until this point
>     const clusters = this.clusterer.getClusters(bounds, zoom);
>     this.log("clusters", clusters) <---- empty
> ```
> 
> Not sure why this.clusterer.getClusters isn't returning the clusters. If you happen to know a potential fix that would be much appreciated, thanks

Yeah I should have mentioned that the carbonmark changes have a dependency on the carbonmark-api changes. So...

1. Setup envs for both projects:

`vercel link` (select carbonmark)
`vercel env pull --environment development carbonmark/.env.local`  (make sure we are putting these vars in carbonmark)

`vercel link` (select carbonmark-api)
`vercel env pull --environment development  .env.local`

2. Run both dev environments at the same time:

`npm run dev-carbonmark-api`

In a seperate terminal:

`NEXT_PUBLIC_CARBONMARK_API_URL=http://localhost:3003/api npm run dev-carbonmark`

2023-08-16 12:51 UTC, jabby09 reviewed
@0xemc a bit more feedback:

1. Is it easy to add a few basic map controls? Zoom in, Zoom out, pan, and full extent controls would be helpful for navigating the map without needing to use track pad gestures.
2. As you click the pins and zoom in, eventually you get to scale where you see a number like "4". If I click that I zoom all the way in and it changes to a clickable project pin. However, there is only 1 project? So where did the "4" come from?
3. On mobile, the full extent of the map is restricted to roughly the image below. I can still pan but cannot zoom out to the full extent
![IMG_C933AC3A7DF9-1](https://github.com/KlimaDAO/klimadao/assets/103535195/8b750c2e-0c98-4b11-9c51-ceeb1791dbcc)

2023-08-16 18:48 UTC, theprofessora commented
finally got a chance to  do some design thinking about this. here: what I came up with. LMK what you think @Atmosfearful and @jabby09 and @0xemc https://www.figma.com/file/5GewbdVaM1Q06CwHmF7d3F?node-id=0:1&mode=design#528675337

2023-08-16 23:04 UTC, 0xemc commented
> finally got a chance to  do some design thinking about this. here: what I came up with. LMK what you think @Atmosfearful and @jabby09 and @0xemc https://www.figma.com/file/5GewbdVaM1Q06CwHmF7d3F?node-id=0:1&mode=design#528675337

Nice, that's much more consistent. 

One thing I would like to do is change the marker for each project to represent the type of project that it is (forestry, etc) so the user knows at first glance what they're looking at, thoughts?

Would be good to have a think about what we can do with hover behaviour and boundaries etc later on

For now I'll clean up the consistency as a minimum

2023-08-28 06:37 UTC, 0xemc commented
> @0xemc a bit more feedback:
> 
> * Is it easy to add a few basic map controls? Zoom in, Zoom out, pan, and full extent controls would be helpful for navigating the map without needing to use track pad gestures.
> * As you click the pins and zoom in, eventually you get to scale where you see a number like "4". If I click that I zoom all the way in and it changes to a clickable project pin. However, there is only 1 project? So where did the "4" come from?
> * On mobile, the full extent of the map is restricted to roughly the image below. I can still pan but cannot zoom out to the full extent
> 
> ![IMG_C933AC3A7DF9-1](https://user-images.githubusercontent.com/103535195/261012906-8b750c2e-0c98-4b11-9c51-ceeb1791dbcc.jpeg)
> 
> * Font on the project cards does not match design system
> 
> ![Screenshot 2023-08-16 at 9 53 28 AM](https://user-images.githubusercontent.com/103535195/261013334-aa08ecb9-9aa0-439c-ba53-f9e78bf25920.png)
> 
> * If I click more info on a project card and go to the project details page, if I click page I'm zoomed out to the full map extent. Is it possible to save the last zoom state and return the user back to that location?
> * Sometimes the pop up cards, the X to close does not have a hover state, but I can't replicate this consistently. Here is one example that happened to me
> 
> ![Screenshot 2023-08-16 at 9 57 36 AM](https://user-images.githubusercontent.com/103535195/261014324-26cfe491-accb-43fc-a034-f639dbd8be0a.png)

@jabby09 this one should be ready to go now.

> Is it easy to add a few basic map controls? Zoom in, Zoom out, pan, and full extent controls would be helpful for navigating the map without needing to use track pad gestures.

I've added zoom controls on the bottom left but pan and fullscreen are a little more work.

> As you click the pins and zoom in, eventually you get to scale where you see a number like "4". If I click that I zoom all the way in and it changes to a clickable project pin. However, there is only 1 project? So where did the "4" come from?

This is unfortunately showing the various vintages for that project. Until we can think of a neat way of showing this I've hidden extra vintages (we should tackle this in a seperate ticket)

> On mobile, the full extent of the map is restricted to roughly the image below. I can still pan but cannot zoom out to the full extent

I believe this is a function of the dimensions of the map. If we were to zoom out further the top and bottom would need to replicate, fold on themselves (i.e north becomes south) or be blacked out.

> Font on the project cards does not match design system

This should be resolved now

> If I click more info on a project card and go to the project details page, if I click page I'm zoomed out to the full map extent. Is it possible to save the last zoom state and return the user back to that location?

We can definitely do this but it's not trivial, perhaps a nice to have in a future ticket?

> Sometimes the pop up cards, the X to close does not have a hover state, but I can't replicate this consistently. Here is one example that happened to me

I noticed this too (it was an overlap issues), should be fixed now.

2023-08-28 19:49 UTC, jabby09 commented
> This is unfortunately showing the various vintages for that project. Until we can think of a neat way of showing this I've hidden extra vintages (we should tackle this in a seperate ticket)

@0xemc sounds good. This will likely resolve itself in v2 of the project pages where we will only have one project and the vintages will be listings on the project (i.e. so not a separate project by vintage)

2023-08-28 19:51 UTC, jabby09 requested changes
@0xemc I saw your comments on my other feedback and all good

One other thing, need to maintain the hover tool tips on these view options...
<img width="191" alt="Screenshot 2023-08-28 at 4 49 58 PM" src="https://github.com/KlimaDAO/klimadao/assets/103535195/d88bab5d-c9bc-4915-9cce-50f0d7609b79">

So for example:
<img width="197" alt="Screenshot 2023-08-28 at 4 50 23 PM" src="https://github.com/KlimaDAO/klimadao/assets/103535195/dbf65a7e-90d5-4b6c-82e0-538992146e16">

2023-08-29 06:54 UTC, 0xemc commented
> @0xemc I saw your comments on my other feedback and all good
> 
> One other thing, need to maintain the hover tool tips on these view options... <img alt="Screenshot 2023-08-28 at 4 49 58 PM" width="191" src="https://user-images.githubusercontent.com/103535195/263818629-d88bab5d-c9bc-4915-9cce-50f0d7609b79.png">
> 
> So for example: <img alt="Screenshot 2023-08-28 at 4 50 23 PM" width="197" src="https://user-images.githubusercontent.com/103535195/263818724-dbf65a7e-90d5-4b6c-82e0-538992146e16.png">

Good pickup, updated 👍

2023-08-29 23:10 UTC, jabby09 approved these changes
looks good

2023-08-30 04:22 UTC, merged