fix recept urls for when retiring on behalf
KlimaDAO/klimadao pull request #1414
Opened 2023-08-14 10:39 UTC by sprrwhwk

## Description

We were using the wallet address of the current user for receipt URLs before. This PR makes it so that we use the beneficiary address if it is provided in the retirement form.

## Related Ticket

Resolves #1370 

## Checklist

- [ ] I have run `npm run build-all` without errors
- [ ] I have formatted JS and TS files with `npm run format-all`

2023-08-15 20:30 UTC, Atmosfearful approved these changes

2023-08-15 20:32 UTC, Atmosfearful requested changes
* [x] Please rename to `beneficiaryAddress` so as not to get confused with beneficiary (name)
* [ ] please remove the `address` prop altogether if you can, I took a quick glance and it looks like you just have to update 1 text block so that it also uses `beneficiaryAddress` instead of `address`

2023-08-16 09:21 UTC, 0xtapi commented
Tested this by retiring a few tonnes, no issues. Beneficiary address, receipts, and URL behave as expected. ✅

2023-08-24 22:19 UTC, Atmosfearful approved these changes

2023-08-24 22:19 UTC, merged