[DRAFT] Makka/1422 change payment methods display
KlimaDAO/klimadao pull request #1459
Opened 2023-08-21 08:32 UTC by 0xMakka

## Description

This is a WIP, the following items are remaining:

- [ ] add credit card processing fee calculation

## Related Ticket

Resolves #1422 

## Changes

| Before  | After  |
|---------|--------|
|<img width="1000" alt="Screenshot 2023-08-21 at 09 31 17" src="https://github.com/KlimaDAO/klimadao/assets/92357475/f419d1d4-9c65-4d30-88bc-8358286c7f10">|<img width="1000" alt="Screenshot 2023-08-21 at 09 31 37" src="https://github.com/KlimaDAO/klimadao/assets/92357475/5307c5d4-ef5b-421e-ab62-77f4c8ebcf85">|

## Checklist

- [X] I have run `npm run build-all` without errors
- [X] I have formatted JS and TS files with `npm run format-all`

2023-08-30 13:07 UTC, jabby09 requested changes
Hey makka

For the use case `Logged Out - Pay with CC` (see 1422 for details), this is what I'm currently seeing in the PR:

<img width="478" alt="Screenshot 2023-08-30 at 10 06 56 AM" src="https://github.com/KlimaDAO/klimadao/assets/103535195/417d22ca-771d-4af8-80e5-1d7a86d724f0">

As per the design, when the form loads, no payment method should be selected yet - is that possible.

And USDC does not have a processing fee. If I'm not logged in, there should be a "Login to pay with USDC" shown on the USDC option.

![image](https://github.com/KlimaDAO/klimadao/assets/103535195/bb5131b0-47b1-4297-89ca-bdb812e44a59)

2023-08-30 13:17 UTC, jabby09 requested changes
For `Logged In` use case...

See this when the form first loads (does not match design) - balance on USDC option should be shown as this point

<img width="497" alt="Screenshot 2023-08-30 at 10 15 58 AM" src="https://github.com/KlimaDAO/klimadao/assets/103535195/b7aa6b8d-2ea8-4379-9819-4f611fd9ba5d">

If I select USDC I see this (not correct, CC does not have a Balance)

<img width="484" alt="Screenshot 2023-08-30 at 10 17 09 AM" src="https://github.com/KlimaDAO/klimadao/assets/103535195/443a68de-c616-40aa-a955-6d48c524c1d1">

2023-09-07 12:35 UTC, jabby09 requested changes
@0xMakka sorry in advance for this but after reviewing the implementation as per the designs, and discussing with atmos, we are going to be making some changes as per below.

**Set Pay with: default to Credit Card**
- While the designs show an empty "pay with" state on form load, in practice this ends up being somewhat of a confusing UX given how the overall form and pricing widget works.
- So for ALL USE CASES (see all the flows in #1422) we will **default the form to load with Credit Card selected** as the default payment method.
- Then if the user starts adding tonnes at the top of the form, all the helper messaging and price updates will function as expected.
- **Note this is exactly how the forms currently works in production**, with Credit Card being the default selection in the Pay with: drop down and the pricing widget showing amounts with $

**Other changes:**
- [x] Pay with: on the forms should have Required Field indicator (red *)
- [x] For non-logged in user, these changes:
- `Login to pay with USDC` option should be clickable and open the login modal
- The primary form button text should be RETIRE CARBON (when you retire, you are not actually doing a BUY)
<img width="495" alt="Screenshot 2023-09-07 at 9 28 50 AM" src="https://github.com/KlimaDAO/klimadao/assets/103535195/04e1b734-9c0c-495d-9296-e6fededcf405">

2023-09-12 12:48 UTC, jabby09 requested changes
@0xMakka 

- For already logged in use case:
- Form looks correct on initial load, CC is the default pay with

If I change the tonnes to 1, getting a total cost error
<img width="937" alt="Screenshot 2023-09-12 at 9 44 18 AM" src="https://github.com/KlimaDAO/klimadao/assets/103535195/9339b534-2815-4375-a434-8771c68d8cb7">

(NOTE: I checked this in Production and also seeing the error so this may have been here already??)

2023-09-12 12:49 UTC, jabby09 requested changes
@0xMakka tool tips (all of them) are wider than component, check Production for comparison

<img width="381" alt="Screenshot 2023-09-12 at 9 49 23 AM" src="https://github.com/KlimaDAO/klimadao/assets/103535195/5d0deaff-fe44-4e02-a640-c6079ef1fb27">

2023-09-12 12:51 UTC, 0xMakka commented
> If I change the tonnes to 1, getting a total cost error

@jabby09 yeah, it's likely this is an issue already in production as I am using the same function for calculating the CC fees that was already there. I'll take a look though and see can I spot what the issue is.

2023-09-12 12:56 UTC, 0xMakka commented
> > likely this is an issue already in production as I am using the same function for calculating the CC fees that was already there. I'll take a look though and see can I spot what the issue is.
> 
> should probably create a new ticket for this one

Sorry looking at this again, the card on the right wasn't changed in this PR (I just use the same function for calculating the processing fee on the payment methods that's used on this card). So yeah I think another ticket to investigate this would be the best option 👍

2023-09-12 12:57 UTC, jabby09 requested changes
@0xMakka 

Non-logged in use case

- Form looks correct on initial load - pay with CC is the default
- If I click the Login to pay with USDC the login modal appears as expected
- If I X the model (i.e. close it) then back on the form I cannot select Credit Card as the pay with option - the modal just keeps opening
- If I complete the login, then back on the form I can change my pay with option
- So it looks like something is going on when the modal pops up that is forcing me to complete the login

2023-09-12 12:58 UTC, 0xMakka commented
> @0xMakka tool tips (all of them) are wider than component, check Production for comparison
> 
> <img alt="Screenshot 2023-09-12 at 9 49 23 AM" width="381" src="https://user-images.githubusercontent.com/103535195/267333609-5d0deaff-fe44-4e02-a640-c6079ef1fb27.png">

This card on the right wasn't changed as part of this PR, so not sure on this one.

For me however, they look the same size on my laptop?

<img width="1512" alt="Screenshot 2023-09-12 at 13 54 20" src="https://github.com/KlimaDAO/klimadao/assets/92357475/218a7c55-ef88-49d9-a160-3e0337ded1c0">

<img width="1512" alt="Screenshot 2023-09-12 at 13 54 26" src="https://github.com/KlimaDAO/klimadao/assets/92357475/d2e29156-cedf-4a20-901b-610856c9bf66">

2023-09-12 13:44 UTC, 0xMakka commented
> @0xMakka
> 
> Non-logged in use case
> 
> * Form looks correct on initial load - pay with CC is the default
> * If I click the Login to pay with USDC the login modal appears as expected
> * If I X the model (i.e. close it) then back on the form I cannot select Credit Card as the pay with option - the modal just keeps opening
> * If I complete the login, then back on the form I can change my pay with option
> * So it looks like something is going on when the modal pops up that is forcing me to complete the login

@jabby09 just pushed some changes which should address this behaviour.

2023-09-23 19:50 UTC, 0xMakka commented
@Atmosfearful when you get a minute, would you mind taking a look at this PR 👍

2023-09-29 14:14 UTC, Atmosfearful approved these changes

2023-10-03 23:45 UTC, merged