Emc/chore/1396-get-projects-test
KlimaDAO/klimadao pull request #1496
Opened 2023-09-01 03:07 UTC by 0xemc

## Description

get /projects jest testing

## Related Ticket

Resolves #1396

<!-- If there are UI changes, please include a before and after screenshot in the following template:

2023-09-01 21:04 UTC, Atmosfearful requested changes
This will conflict heavily with my changes to get so let me get that up and we can find the smoothest path to integrate

2023-09-01 21:39 UTC, 0xemc commented on carbonmark-api/src/.generated/mocks/marketplace.mocks.ts
> +        singleUnitPrice: overrides && overrides.hasOwnProperty('singleUnitPrice') ? overrides.singleUnitPrice! : 40,
Spent some time fighting the generator to produce a string representation of a number but no bueno. I've updated the forced '

2023-09-05 11:30 UTC, sprrwhwk approved these changes
Great work, love the tests 👍

2023-09-08 17:59 UTC, Atmosfearful commented on carbonmark-api/src/utils/helpers/carbonProjects.utils.ts
> +  const [{ allProject = [] }, { allProjectContent = [] }] = await Promise.all([
It's 'default parameter syntax'
if either of those values are `undefined`, they will instantiate an empty array instead

2023-09-08 18:01 UTC, Atmosfearful commented on carbonmark-api/src/utils/helpers/carbonProjects.utils.ts
> +  const [{ allProject = [] }, { allProjectContent = [] }] = await Promise.all([
Destructure syntax needs to use the underlying property name, in this case allProject and allProjectContent are correct. If the goal is to rename the property after destructuring it, that uses a colon;
```
const { existingProp: newPropName } = obj;
```

2023-09-14 00:27 UTC, closed without merging