set correct content type header for project endpoint
KlimaDAO/klimadao pull request #1982
Opened 2023-12-06 07:47 UTC by sprrwhwk

## Description

This PR sets the content type header for the project-by-id endpoint to `application/json`. Currently it's not being set correctly: https://api.carbonmark.com/projects/VCS-1529-2012.

## Related Ticket

Closes <issue-number>
Also related to <issue-number>

## Notes For QA

Specific pages, components or journeys that might be affected:
- 

Relevant preview URLs:
- 

Other notes:
-

2023-12-11 06:37 UTC, biwano approved these changes

2023-12-11 17:35 UTC, 0xemc approved these changes

2023-12-11 17:35 UTC, 0xemc requested changes
Small thing but this might need a patch bump on the version number

2023-12-13 15:46 UTC, 0xemc approved these changes

2023-12-13 15:53 UTC, merged