fix activity designs
KlimaDAO/klimadao pull request #2066
Opened 2024-01-03 18:44 UTC by sprrwhwk

## Description
This PR fixes general problems with the activity feed:

* Adds the `t` to quantities for quantity updates
* Makes the UI look more like the figma design in general

|Before|After|
|---|---|
|<img width="360" alt="grafik" src="https://github.com/KlimaDAO/klimadao/assets/138768831/b08985cc-c191-4b73-a123-185d51d2661c">|<img width="356" alt="grafik" src="https://github.com/KlimaDAO/klimadao/assets/138768831/10f52c6f-7fa5-467a-b6d5-cdef1e8eb653">|
|<img width="155" alt="grafik" src="https://github.com/KlimaDAO/klimadao/assets/138768831/e63d4b58-4dad-4539-97e1-dfdf139244fb">|<img width="131" alt="grafik" src="https://github.com/KlimaDAO/klimadao/assets/138768831/9ed991a9-8a1f-453a-a59a-2d86d562ef39">|

## Related Ticket

Closes #2039

2024-01-03 18:46 UTC, sprrwhwk commented
cc @theprofessora

2024-01-03 19:01 UTC, jabby09 requested changes
@sprrwhwk very nice, looks much better

Only think I could see (compared to the designs) is the light blue frame should alternate, so in this example activity 1, 3, and 5 would have the blue backing but activity 2 and 4 would not.

<img width="370" alt="Screenshot 2024-01-03 at 2 59 38 PM" src="https://github.com/KlimaDAO/klimadao/assets/103535195/5d8b4afd-8a3d-455f-8da1-09fd760a4a64">

2024-01-03 19:16 UTC, sprrwhwk commented
> @sprrwhwk very nice, looks much better
> …

Fixed in the latest commit

2024-01-04 13:27 UTC, jabby09 approved these changes

2024-01-05 14:11 UTC, 0xemc approved these changes

2024-01-05 23:53 UTC, merged