Fix moss single retirement page
KlimaDAO/klimadao pull request #2118
Opened 2024-01-13 11:55 UTC by biwano

## Description

## Related Ticket

Closes <issue-number>
Also related to <issue-number>

## Notes For QA

Specific pages, components or journeys that might be affected:
- 

Relevant preview URLs:
- 

Other notes:
-

2024-01-15 11:14 UTC, sprrwhwk approved these changes

2024-01-15 13:23 UTC, 0xemc approved these changes

2024-01-15 13:40 UTC, jabby09 requested changes
@biwano 
This fix worked for the wallet you provided

However I still do not see my Moss retirements in these wallets
https://carbonmark-git-fixmosssingleretirementpage-klimadao.vercel.app/retirements/0x6476edf98bdc5ee62f9d4e4bf8932d69ed685483

https://carbonmark-git-fixmosssingleretirementpage-klimadao.vercel.app/retirements/brice.klima

2024-01-16 13:40 UTC, jabby09 reviewed
@biwano is this working now for all wallet addresses?

For example, here are two moss retirements from the klima data but I don't see these on the receipt pages https://data.klimadao.finance/retirement-trends

0xdd68a3bdad2d75fdfae4ef2a65215beac59f86cc | N/A | MCO2 | 1/9/2024 | 1.71 | 
https://carbonmark-git-fixmosssingleretirementpage-klimadao.vercel.app/en/retirements/0xdd68a3bdad2d75fdfae4ef2a65215beac59f86cc

0x556fb759c5c22f10f51814c4c1f9cd58650615a8 | N/A | MCO2 | 1/3/2024 | 3.49 |  
https://carbonmark-git-fixmosssingleretirementpage-klimadao.vercel.app/en/retirements/0x556fb759c5c22f10f51814c4c1f9cd58650615a8

Yet this one does work??
0xdf86dd437d5b09ad0601de176a77afb4b90ff702 | N/A | MCO2 | 1/6/2024 | 10.00 |
https://carbonmark-git-fixmosssingleretirementpage-klimadao.vercel.app/en/retirements/0xdf86dd437d5b09ad0601de176a77afb4b90ff702

2024-01-16 15:06 UTC, biwano commented
> @biwano is this working now for all wallet addresses?
> 
> For example, here are two moss retirements from the klima data but I don't see these on the receipt pages https://data.klimadao.finance/retirement-trends
> 
> 0xdd68a3bdad2d75fdfae4ef2a65215beac59f86cc | N/A | MCO2 | 1/9/2024 | 1.71 | https://carbonmark-git-fixmosssingleretirementpage-klimadao.vercel.app/en/retirements/0xdd68a3bdad2d75fdfae4ef2a65215beac59f86cc
> 
> 0x556fb759c5c22f10f51814c4c1f9cd58650615a8 | N/A | MCO2 | 1/3/2024 | 3.49 |   https://carbonmark-git-fixmosssingleretirementpage-klimadao.vercel.app/en/retirements/0x556fb759c5c22f10f51814c4c1f9cd58650615a8
> 
> Yet this one does work?? 0xdf86dd437d5b09ad0601de176a77afb4b90ff702 | N/A | MCO2 | 1/6/2024 | 10.00 | https://carbonmark-git-fixmosssingleretirementpage-klimadao.vercel.app/en/retirements/0xdf86dd437d5b09ad0601de176a77afb4b90ff702

For these cases I can find Retire instances in the subgraph but no KlimaRetire instances.
@cujowolf @0xAurelius maybe is it linked with the issue of mlissing Retire instances in the subgraph?

```"retires": [
      {
        "bridgeID": null,
        "klimaRetire": null,
        "hash": "0x2361d9fae4e971663f56eb1dfaa301914bfd7227a351a9b298c96b1a72d33af6",
        "amount": "1329977443968608766",
        "beneficiaryAddress": {
          "id": "0x556fb759c5c22f10f51814c4c1f9cd58650615a8"
        },
        "timestamp": "1677827207",
        "pool": {
          "name": "Moss Carbon Credit (PoS)",
          "id": "0xaa7dbd1598251f856c12f63557a4c4397c253cea"
        }
      }```

2024-01-17 09:56 UTC, 0xMakka approved these changes

2024-01-25 13:46 UTC, jabby09 approved these changes

2024-01-25 15:37 UTC, merged