Add doppler config and update README
KlimaDAO/klimadao pull request #2187
Opened 2024-01-26 22:24 UTC by 0xemc

## Description

Doppler config for `carbonmark-api`

2024-01-26 22:30 UTC, 0xemc commented
@biwano if you have some time could you test this out by following the instructions in the `carbonmark-api/README.md`?

I also sent you an invite to doppler to your bruno@carbonmark.com email

2024-01-30 14:50 UTC, sprrwhwk requested changes
I would link to the installation docs instead. I know at least one team member who's using windows 😄

2024-01-30 14:50 UTC, sprrwhwk commented on carbonmark-api/README.md
> +Install the doppler CLI
```suggestion
[Install the doppler CLI](https://docs.doppler.com/docs/install-cli#installation)
```

2024-01-31 17:35 UTC, biwano commented
> @biwano if you have some time could you test this out by following the instructions in the `carbonmark-api/README.md`?
> 
> I also sent you an invite to doppler to your [bruno@carbonmark.com](mailto:bruno@carbonmark.com) email

@0xemc  It worked for me.

2024-02-02 11:53 UTC, 0xemc commented
Converting to draft as we would need to provide everyone with doppler logins in order to locally develop

2024-02-02 14:36 UTC, sprrwhwk approved these changes

2024-02-05 09:53 UTC, 0xemc commented
Closing this in favour of https://vercel.com/changelog/sensitive-environment-variables-are-now-available

2024-02-05 09:53 UTC, closed without merging