Remove ICR API from filters (and carbonmark-api)
KlimaDAO/klimadao pull request #2250
Opened 2024-02-09 14:52 UTC by psparacino

## Description

Now that all ICR projects are on the subgraph, the countries, vintages and methodologies for those projects are on the subgraph and we no longer need to query ICR's api for the available filters.

This PR removes the last remaining piece of the ICR api from `carbonmark-api` so that all ICR sources, (except querying user ICR holdings) are either from the CM cms or subgraphs.

## How to Test

1. On the preview link go to `/projects`
2. Filter by 'Spain'
3. The only result is an ICR project

## Notes For QA

Other notes:
- There shouldn't be any change in behavior, as the ICR api calls for filters had become redundant

2024-02-12 08:26 UTC, 0xemc commented on carbonmark-api/src/app.constants.ts
As @biwano often mentions we should use the `npm version patch` command or run `npm install` after changing this to make sure that the package-lock is updated correctly

2024-02-12 08:54 UTC, biwano approved these changes
Nice.
Can you update the version package-lock.json too?
To do so when you update you can use the command `npm version patch` in the `carbonmark-api` folder. It updates both the `package.json` and the `package-lock.json`.

2024-02-12 09:01 UTC, biwano requested changes
I connected carbonmark to the preview API in vercel and it made the PR crash.

2024-02-12 13:53 UTC, psparacino commented on carbonmark-api/src/app.constants.ts
hm that's only updating the package.json and not package-lock for me.

2024-02-19 06:35 UTC, biwano approved these changes

2024-02-19 06:37 UTC, merged