base updates
KlimaDAO/klimadao pull request #2383
Opened 2024-07-29 14:47 UTC by 0xMakka

## Description

This PR includes changes discussed in discord to base, i.e.

- Add a "Retire on base" button in the main KD dApp.
- Emphasise the "proof-of-concept" text

2024-07-29 17:32 UTC, jabby09 approved these changes

2024-07-30 10:33 UTC, 0xtapi commented
Just something to add: The "emphasized" part doesn't seem to work for me:
![Screenshot 2024-07-30 123039](https://github.com/user-attachments/assets/56473e99-1f8e-4dc1-b3a6-eb55a99bfeca)

Still looks like non-emphasized text to me 🤔

2024-07-30 10:39 UTC, 0xMakka commented
> Just something to add: The "emphasized" part doesn't seem to work for me: ![Screenshot 2024-07-30 123039](https://private-user-images.githubusercontent.com/128430614/353423393-56473e99-1f8e-4dc1-b3a6-eb55a99bfeca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzMzYyMzYsIm5iZiI6MTcyMjMzNTkzNiwicGF0aCI6Ii8xMjg0MzA2MTQvMzUzNDIzMzkzLTU2NDczZTk5LTFmOGUtNGRjMS1iM2E2LWViNTVhOTliZmVjYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDczMFQxMDM4NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YTZjM2U5YWNiMzU3NmRlNGM2MGJiM2ZlMTVjOTNlNWJmYWU1MjBhY2RkMWNhMDBmOGU4OWMyNzk2MDJmODM0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.lAYZapEVAMx_21_YvIHoWSnq98zHRNUc6PSoKofymNM)
> 
> Still looks like non-emphasized text to me 🤔

@0xtapi are you using the base preview link above? - https://base-git-makka-base-updates-klimadao.vercel.app/

2024-07-30 10:43 UTC, 0xtapi commented
> @0xtapi are you using the base preview link above?

Ah... No, I used the other one and expected to be taken to the same destination. Alright, false alarm 🫡

2024-07-30 15:35 UTC, Atmosfearful requested changes

2024-07-30 15:35 UTC, Atmosfearful commented on app/components/NavMenu/index.tsx
> +            href="https://base-poc.vercel.app"
url is configured:
```suggestion
            href="https://base.klimadao.finance"
```

2024-07-30 16:09 UTC, Atmosfearful approved these changes

2024-07-30 16:09 UTC, merged