auto-compounder feature
KlimaDAO/klimadao pull request #2394
Opened 2024-11-10 11:10 UTC by must-be-carbon

## Description

[](https://github.com/KlimaDAO/klimadao/issues/2393)

## Related Ticket

Closes [2393](https://github.com/KlimaDAO/klimadao/issues/2393)

## How to Test
- Go to URL
- View Deposit list to see eligible tokens to stake to 
- Go to Your Positions tab to view All positions and then Attempt to withdraw. 

## Notes For QA
1. Test AutoCompounder Deposit + Withdraw flows
2. Test Existing Cross Chain Retirement 

Specific pages, components or journeys that might be affected:
- Base Retirement section of the existing base dapp

Relevant preview URLs:
- 

Other notes:
-

2024-11-11 15:35 UTC, jabby09 requested changes
@0xMakka 
see my discord comment here with screenshots https://discord.com/channels/1135827610434289727/1275053162599809024/1305554232924962937

- please do a full pass through the app and update the terminology using this as a guide/template
![image](https://github.com/user-attachments/assets/45c39615-c3a2-4ab5-93dd-6db5c9445d76)

other screens that I see need changes:
- https://base-git-feat-auto-compounder-klimadao.vercel.app/auto-compounder/deposit/all

2024-11-11 20:33 UTC, jabby09 requested changes
@0xMakka found a few more things... 

- [x] on this dialog, change copy to `Approval confirmed; ready to stake.`
- [ ] also the tabs should just be labels, not items that when I hover looks like I can click them. should only be able to click the APPROVE and STAKE buttons at bottom of the form
![Screenshot 2024-11-11 at 4 33 17 PM](https://github.com/user-attachments/assets/66921a33-6ccb-4619-b297-e4d98a90b224)

2024-11-11 20:37 UTC, jabby09 requested changes
@0xMakka 

- [ ] on Your Positions screen, change WITHDRAW to UNSTAKE
![Screenshot 2024-11-11 at 4 36 06 PM](https://github.com/user-attachments/assets/48cb7574-5c4f-47ea-8f2b-93955baf36fa)

- [ ] After I complete a STAKE transaction, the user should be redirected to Your Positions tab, on the Auto Compounder / STAKE tab

2024-11-12 09:54 UTC, 0xMakka commented
@jabby09 All changes you requested should now be ready to test again.

2024-11-12 17:33 UTC, jabby09 requested changes
@0xMakka another round of UI tweeks to [match designs](https://www.figma.com/design/K6j7MnRHQrlDg6Ic79pAJc/Auto-Compounder?node-id=1-3&node-type=canvas&t=yE9XFtbRbOTT925c-0)

- [x] on Auto Compounder modal, in the [Pool dropdown](https://www.figma.com/design/K6j7MnRHQrlDg6Ic79pAJc/Auto-Compounder?node-id=1-609&t=yE9XFtbRbOTT925c-4), supposed to be showing TVL and APR

2024-11-12 17:36 UTC, jabby09 requested changes
@0xMakka quite a few changes on the Your Positions screen to match designs

See https://www.figma.com/design/K6j7MnRHQrlDg6Ic79pAJc/Auto-Compounder?node-id=28-817&t=yE9XFtbRbOTT925c-4

vs

<img width="1100" alt="Screenshot 2024-11-12 at 1 36 06 PM" src="https://github.com/user-attachments/assets/f0461a00-7a97-4a23-b018-ae61dce200c9">

NOTE: Withdraw in designs should now be Unstake

2024-11-13 13:08 UTC, 0xMakka commented
> @0xMakka quite a few changes on the Your Positions screen to match designs
> 
> See https://www.figma.com/design/K6j7MnRHQrlDg6Ic79pAJc/Auto-Compounder?node-id=28-817&t=yE9XFtbRbOTT925c-4
> 
> vs
> 
> <img alt="Screenshot 2024-11-12 at 1 36 06 PM" width="1100" src="https://private-user-images.githubusercontent.com/103535195/385396060-f0461a00-7a97-4a23-b018-ae61dce200c9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0ODQ2ODUsIm5iZiI6MTczMTQ4NDM4NSwicGF0aCI6Ii8xMDM1MzUxOTUvMzg1Mzk2MDYwLWYwNDYxYTAwLTdhOTctNGEyMy1iMDE4LWFlNjFkY2UyMDBjOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExM1QwNzUzMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYjM2MTg3ZmEzNWQxNTljMTRmZmNhZGNkMTI3ZGQ5YjcwMmY5NmRiOTVjZGE4YzMxMTU2YzJiOGExMDNhYzg2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.2qJFKeKmrVbcY6Y0jjHWT82JOyfJ10Y04yTobhi6E9E">
> NOTE: Withdraw in designs should now be Unstake

@jabby09 I'm not sure this information is available from the smart contract to match the figma designs on the "Your positions" tab. Before Abhijeet left he mentioned I believe that being able to calculate the number of vault tokens available for example would require a subgraph call which he wanted to avoid. However, I'll take a look at which pieces of data are currently missing and see what information I am able to add (if any) that is currently missing.

2024-11-13 13:16 UTC, jabby09 commented
> However, I'll take a look at which pieces of data are currently missing and see what information I am able to add (if any) that is currently missing.

@0xMakka sounds good. the most important part to add if possible would be the yield accrued since the entire point of auto compounding.

2024-11-13 13:32 UTC, must-be-carbon commented
@0xMakka @jabby09 the current smart contracts don't store entry time deposit at the moment. 

We will need to fallback to using something like graph for this purpose or filter events on the frontend which is not scalable. As the number of blocks increases filtering process will take longer. 

IMO, we need to take a call to introduce graph or offload yield calculations to the user itself for time being.

I also think adding subgraph shouldn't be so hard but yeah given we will have multiple pools and multiple tokens it might get complicated

2024-11-13 13:49 UTC, jabby09 commented
> IMO, we need to take a call to introduce graph or offload yield calculations to the user itself for time being.
> 
> I also think adding subgraph shouldn't be so hard but yeah given we will have multiple pools and multiple tokens it might get complicated

@must-be-carbon okay understood. I can confirm with Scott that we release the MVP with no subgraph support and then we can follow up with additional phases to ensure the app matches the designs.

2024-11-13 14:00 UTC, jabby09 requested changes
@0xMakka I requested that we add Success! screens to the flow

### Stake flow
- [x] [design](https://www.figma.com/design/K6j7MnRHQrlDg6Ic79pAJc/Auto-Compounder?node-id=303-3310&t=6D86NxSV9SH3gLzY-4)
### Unstake flow
- [x] [design](https://www.figma.com/design/K6j7MnRHQrlDg6Ic79pAJc/Auto-Compounder?node-id=303-3379&t=6D86NxSV9SH3gLzY-4)

2024-11-15 08:56 UTC, 0xtapi commented
## Button alignments
The `CONNECT` button (first screenshot) should be centered, imo. Also, when the user is connected, something about those two buttons (second screenshot) doesn't seem quite right to me, but I can't really put my finger on it. Maybe make them the same size? Happy to leave it like that if no one else has any objections 🫡 
<img width="271" alt="Screenshot_20241115-091301" src="https://github.com/user-attachments/assets/ca495c5e-4fd7-4410-9246-2ac5f99a0a5d">
<img width="271" alt="Screenshot_20241115-092600" src="https://github.com/user-attachments/assets/f5bab5c3-82a4-4c25-bb2d-9e53f4b2ca79">

## Yield not loading
On mobile, APR isn't loading/displaying. APY works though.
![Screenshot_20241115-091244](https://github.com/user-attachments/assets/fab2f1d7-e2b4-4a5f-8dce-5181a646c8ae)

## Too much KlimaDAO?
In the retire section of the app, we show "KlimaDAO" twice at the top, once as part of the nav bar, once on the page itself. Maybe remove the second one and he `CONNECT` button (since we have that in the menu already)?
![Screenshot_20241115-091342](https://github.com/user-attachments/assets/f5a47d8c-1263-4d45-98c8-3a46d55d5eae)

## Can't tap info elements
The little circeled question mark elements (see screenshot) can't really be tapped with a finger, or maybe it's just my fingers (remember the "Your fingers are too fat to dial" Simpsons episode?).
![Screenshot_20241115-091426](https://github.com/user-attachments/assets/f8b996d1-4a41-4f5f-89df-2970bf07b54f)

## Unstake button
Would be nice if the Unstake button could stretch across the entire element 🤔 Same applies to the Stake button (see screenshots further up).
![Screenshot_20241115-092619](https://github.com/user-attachments/assets/8812a7f4-df6c-41c4-bf7f-e8d582768c3d)

## Language button
The language button (I assume that is what the globe in the nav bar is) is not doing anything right now.

2024-11-15 10:07 UTC, 0xMakka commented
> ## Button alignments
> The `CONNECT` button (first screenshot) should be centered, imo. Also, when the user is connected, something about those two buttons (second screenshot) doesn't seem quite right to me, but I can't really put my finger on it. Maybe make them the same size? Happy to leave it like that if no one else has any objections 🫡 <img alt="Screenshot_20241115-091301" width="271" src="https://private-user-images.githubusercontent.com/128430614/386519150-ca495c5e-4fd7-4410-9246-2ac5f99a0a5d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2NjM5MTcsIm5iZiI6MTczMTY2MzYxNywicGF0aCI6Ii8xMjg0MzA2MTQvMzg2NTE5MTUwLWNhNDk1YzVlLTRmZDctNDQxMC05MjQ2LTJhYzVmOTlhMGE1ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNVQwOTQwMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMzc0OWQwMjFhYTBmZmQxYTE1NjcyYzhjMzY3MDI5NmNhYTMwYzAyOTI5YTU1MDljMmMxMWQwOGE4Yjk4MTNlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.LCPCchiN3UcCKwI46Fvwuq_syTJ7dSFCcz1R-V9-2xk"> <img alt="Screenshot_20241115-092600" width="271" src="https://private-user-images.githubusercontent.com/128430614/386519164-f5bab5c3-82a4-4c25-bb2d-9e53f4b2ca79.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2NjM5MTcsIm5iZiI6MTczMTY2MzYxNywicGF0aCI6Ii8xMjg0MzA2MTQvMzg2NTE5MTY0LWY1YmFiNWMzLTgyYTQtNGMyNS1iYjJkLTllNTNmNGIyY2E3OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNVQwOTQwMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lY2U3OGViNzZiODdlNzM0MTljZjhhMGEwNDhjM2M1YmIwNTQwZmRkMzIzMDMwMzBhYzk1OWYwZjRmOWUxM2U2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.h9H8P6EEd5FZ7EPCtc64LyNdgorcQXT4xLZFu2KFcuU">
> 
> ## Yield not loading
> On mobile, APR isn't loading/displaying. APY works though. ![Screenshot_20241115-091244](https://private-user-images.githubusercontent.com/128430614/386519578-fab2f1d7-e2b4-4a5f-8dce-5181a646c8ae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2NjM5MTcsIm5iZiI6MTczMTY2MzYxNywicGF0aCI6Ii8xMjg0MzA2MTQvMzg2NTE5NTc4LWZhYjJmMWQ3LWUyYjQtNGE1Zi04ZGNlLTUxODFhNjQ2YzhhZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNVQwOTQwMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xOThiMDQ4OTk4MGU2ZWZkOWJmNTYxNWEwOTQ5YzBkODU1NDNmZjVjYzZlMzkzNGVkNDQ4NzNmYWVhNzNjY2M4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.6-hkRopz8boCbARC483v-yTvDCEec8tx5qvp1hlVFK0)
> 
> ## Too much KlimaDAO?
> In the retire section of the app, we show "KlimaDAO" twice at the top, once as part of the nav bar, once on the page itself. Maybe remove the second one and he `CONNECT` button (since we have that in the menu already)? ![Screenshot_20241115-091342](https://private-user-images.githubusercontent.com/128430614/386519797-f5a47d8c-1263-4d45-98c8-3a46d55d5eae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2NjM5MTcsIm5iZiI6MTczMTY2MzYxNywicGF0aCI6Ii8xMjg0MzA2MTQvMzg2NTE5Nzk3LWY1YTQ3ZDhjLTEyNjMtNGQ0NS05OGM4LTNhNDZkNTVkNWVhZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNVQwOTQwMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZDQzZmQ2MDUzMzk0YjEwYzMzYWZjZTViYjQzMjFiZmY5MTE1NGEwNTcxNDkyNGI1Y2FmOTNjYzVhYTExOTZkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.H58YV7pfFgtIkj1i03ux-X3r5C8tJgvfZo3b5rm5BdQ)
> 
> ## Can't tap info elements
> The little circeled question mark elements (see screenshot) can't really be tapped with a finger, or maybe it's just my fingers (remember the "Your fingers are too fat to dial" Simpsons episode?). ![Screenshot_20241115-091426](https://private-user-images.githubusercontent.com/128430614/386522194-f8b996d1-4a41-4f5f-89df-2970bf07b54f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2NjM5MTcsIm5iZiI6MTczMTY2MzYxNywicGF0aCI6Ii8xMjg0MzA2MTQvMzg2NTIyMTk0LWY4Yjk5NmQxLTRhNDEtNGY1Zi04OWRmLTI5NzBiZjA3YjU0Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNVQwOTQwMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZmRmYzk3YjY1MjdiMWU0Y2NmZDBjYzkyNWZkZGJjN2M4ODgzMzExMTY0NTQ2NTIyNjdkNjBjYzZjOGNmOTViJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.NVCrwdWld6-h145xVLRRds9EPT8nOjUYdANg3n3azG0)
> 
> ## Unstake button
> Would be nice if the Unstake button could stretch across the entire element 🤔 Same applies to the Stake button (see screenshots further up). ![Screenshot_20241115-092619](https://private-user-images.githubusercontent.com/128430614/386523069-8812a7f4-df6c-41c4-bf7f-e8d582768c3d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2NjM5MTcsIm5iZiI6MTczMTY2MzYxNywicGF0aCI6Ii8xMjg0MzA2MTQvMzg2NTIzMDY5LTg4MTJhN2Y0LWRmNmMtNDFjNC1iZjdmLWU4ZDU4Mjc2OGMzZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNVQwOTQwMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMzNhYmZhMjc4YWNmNzk1N2RkODg3ZTVjMjJmMTRkNzlhYWUzZjY3NzZlYTUxZmMyMjE3ZWIzNDY2MmQzOTQ5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.RjGbs_4MR6qwIh93vlyZ5d4O-TJ7HjYonQkF5P36JWE)
> 
> ## Language button
> The language button (I assume that is what the globe in the nav bar is) is not doing anything right now.

@0xtapi I've pushed some fixes for the following items:

-[ ] Language button - although it's in the designs we don't support translations at the moment. Not sure if it's necessary for launch, it was never included in the initial retire on base poc. I've removed the button for now.

-[ ] Stake/Unstake button - I've adjusted the width to take 100% of the available width on mobile.

-[ ] Remove the KlimaDAO logo and connect button from the top of the retire page on mobile as it's already in the sidebar as you mentioned.

-[ ] Connect button alignment - I've removed the network button. Initially we talked about another network hence why this button was here. This site is specific to base so I believe the button is now unnecessary. I've removed it and made the connect button take 100% width of the sidebar.

The remaining items on that list will take a bit more time to fix. Tapping icons on mobile is an issue for sure, I can't click them either so need to investigate why they aren't working on mobile. Yield is the same.

2024-11-15 14:15 UTC, 0xMakka commented
> One of the fixes must've broken something else 🤔 This is what the Unstake modal looks like now on desktop: <img alt="Screenshot 2024-11-15 144317" width="326" src="https://private-user-images.githubusercontent.com/128430614/386624422-c1a2ad34-cca0-4994-ba59-e0acd717b8e1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2ODAzOTIsIm5iZiI6MTczMTY4MDA5MiwicGF0aCI6Ii8xMjg0MzA2MTQvMzg2NjI0NDIyLWMxYTJhZDM0LWNjYTAtNDk5NC1iYTU5LWUwYWNkNzE3YjhlMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNVQxNDE0NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZGNjM2UxMjk0OWNmNjExMmQyOTMyZDJmYWIzOWViNjUyNzNjZDhmNmE5ODZmOGM3NjdhNGVlMzhiNjNkNmYxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.l6i1VfLf35kM1twewYHkyDg_6P67__Mv9AzeTCIu0pY">

Sorry sir, I was converting pixel units to rem and set the width incorrectly on a few elements - used 32px for example instead of 320px. Have updated this value, will go through everything again to ensure they are also correct.

2024-11-19 14:00 UTC, jabby09 requested changes
@0xMakka 
anywhere we show info icons on desktop they should show on mouse hover, not mouse click. Examples below but this should be a global change.
![Screenshot 2024-11-19 at 9 59 52 AM](https://github.com/user-attachments/assets/0c7d1b30-9158-481c-812f-326ecb9580b6)

2024-11-19 14:02 UTC, 0xMakka commented
> @0xMakka anywhere we show info icons on desktop they should show on mouse hover, not mouse click. Examples below but this should be a global change. ![Screenshot 2024-11-19 at 9 59 52 AM](https://private-user-images.githubusercontent.com/103535195/387684940-0c7d1b30-9158-481c-812f-326ecb9580b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwMjUyMDksIm5iZiI6MTczMjAyNDkwOSwicGF0aCI6Ii8xMDM1MzUxOTUvMzg3Njg0OTQwLTBjN2QxYjMwLTkxNTgtNDgxYy04MTJmLTMyNmVjYjk1ODBiNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExOVQxNDAxNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYzViMzYxODcyMTk4YzExNThiMjk1YzhmNTZjMDM1MTZhNWI4NTZjNDI3NTIyOTBmMDQ5Mzk4NGY5YjkzNjFhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.dTnQt3cwLG1x83Kj6oiaBpkN91iihZiW4B149jdw7gc)

Hmm, apologies they did show on hover previously. This could be a knock on effect of my changes to get this working on mobile. Taking a look now.

2024-11-19 14:05 UTC, jabby09 requested changes
@0xMakka 
![Screenshot 2024-11-19 at 10 03 56 AM](https://github.com/user-attachments/assets/5d2f5e6b-e99a-4f35-8c6a-28efb6a0ba0d)
As per [designs](https://www.figma.com/design/K6j7MnRHQrlDg6Ic79pAJc/Auto-Compounder?node-id=303-3310&t=nltu30AxdKWiM8ks-4), the title of these modals should include the check icon and exclamation point

2024-11-19 14:28 UTC, jabby09 requested changes
@0xMakka Please add the following link CTAs for docs and faq, see desktop and mobile designs

https://www.figma.com/design/K6j7MnRHQrlDg6Ic79pAJc/Auto-Compounder?node-id=303-664&t=nltu30AxdKWiM8ks-4
https://www.figma.com/design/K6j7MnRHQrlDg6Ic79pAJc/Auto-Compounder?node-id=303-934&t=nltu30AxdKWiM8ks-4

links
Docs = https://docs.klimadao.finance/auto-compounder/auto-compounder-app-guide-draft
FAQ = https://docs.klimadao.finance/auto-compounder/auto-compounder-faq-draft

2024-11-21 20:54 UTC, jabby09 approved these changes

2024-11-21 20:56 UTC, merged