replaced emoji with utf8 code for emoji for linux bug
KlimaDAO/klimadao pull request #428
Opened 2022-05-18 16:54 UTC by goatsOnDrugs

## Description

I replaced the emoji with the code for the emoji to display on linux/ubuntu with brave. I have not tested this bc I dont run linux.

## Related Ticket
#384

Resolves #384 
#384

## Checklist

- [x] Building the site with `npm run build-site` works without errors
- [x] Building the app with `npm run build-app` works without errors
- [x] I formatted JS and TS files with running `npm run format-all`

2022-05-18 16:54 UTC, goatsOnDrugs commented
@ShimonD-KlimaDAO can you test this please and thanks?

2022-05-19 00:00 UTC, Atmosfearful requested changes
Let's just erase the emoji and say no more emojis from now on. I regret ever using them lol. We will stick to MUI icons.
We can erase the others as we come across them.

2022-05-19 18:23 UTC, goatsOnDrugs commented
Emoji deleted

2022-05-19 22:03 UTC, Atmosfearful approved these changes

2022-05-19 22:03 UTC, merged