add podcast to cms and site
KlimaDAO/klimadao pull request #490
Opened 2022-06-15 17:03 UTC by goatsOnDrugs

## Description
Podcasts were added to the cms. Styles are almost the exact same as blog. the podcasts accepts title, publishedAt, summary, and embedCode. I used all spotify embed codes but any embed code would work. I used dangerously set inner html but I think it will be ok since site is all brochure. 

## #313 

Resolves #313 

## Checklist

- [ ] Building the site with `npm run build-site` works without errors
- [ ] Building the app with `npm run build-app` works without errors
- [ ] I formatted JS and TS files with running `npm run format-all`

2022-06-17 22:43 UTC, Atmosfearful requested changes

2022-07-13 14:55 UTC, goatsOnDrugs commented
@Atmosfearful I think this one is good to go. @Go-Mori and I need to look at the mobile nav to see if he is ok with it but it now no longer breaks mobile view with the width being too large.

2022-07-15 05:56 UTC, Atmosfearful requested changes
Desktop cards are too wide now (or maybe I'm just noticing it now), should match the Blog cards. I am able to fix it with just two quick css properties on the outer section element. See the `element.style` overrides in this screenshot, i copypasta'd that grid from /Blog
![image](https://user-images.githubusercontent.com/88635679/179159342-2ed1d3e8-1927-4402-93ea-eea2a28d9753.png)

And on mobile, looks better if the iframe goes 100% width to fill the card

![image](https://user-images.githubusercontent.com/88635679/179160173-9624b67c-7727-41c2-9caf-2e699bdf2379.png)

2022-07-18 18:55 UTC, Atmosfearful approved these changes

2022-07-18 18:56 UTC, merged