[DRAFT] ki landing page
KlimaDAO/klimadao pull request #493
Opened 2022-06-16 20:54 UTC by goatsOnDrugs

## Description

WIP
- created secondary buttons and added "blue" variant to both
- created a page for ki landing page and did the first section

UP NEXT:
1. switch "Enter app" button with "contact sales"
2. add the blue fade to the background
3. next section: create cards
4. make cards scroll nice
## Related Ticket

Resolves #<issue-number>

## Checklist

- [ ] Building the site with `npm run build-site` works without errors
- [ ] Building the app with `npm run build-app` works without errors
- [ ] I formatted JS and TS files with running `npm run format-all`

2022-06-16 20:54 UTC, goatsOnDrugs commented
![image](https://user-images.githubusercontent.com/24912886/174161935-cfc0f97b-6774-432e-a67a-51e3c2131652.png)

2022-07-15 10:18 UTC, ladytrekker approved these changes
Thanks. I can feel the sweat which comes when dealing with Next and its Images 👍 

I can see a lot of refactorings. But as @Atmosfearful pointed out this can be done in follow-up PRs, everything looks so far fine in my eyes.

I did not do intensive browser testings though and would recommend to wait for someone to do that first before merging to staging.

2022-07-15 10:18 UTC, ladytrekker commented on site/components/pages/Infinity/index.tsx
> +              href="https://klima-dao.notion.site/Welcome-to-Klima-Infinity-f2626cb26a474e879287038662e83e47"
I would put all links related to anything with KlimaDAO to the constants file

2022-07-15 10:18 UTC, ladytrekker commented on site/components/pages/Infinity/index.tsx
> +              href="https://notionforms.io/forms/klimadao-request-for-collaboration"
This one too

2022-07-15 10:18 UTC, ladytrekker commented on site/components/pages/Infinity/index.tsx
> +              href="https://www.klimadao.finance/blog/klima-infinity-faqs"
This one too to constants

2022-07-15 10:18 UTC, ladytrekker commented on site/components/pages/Infinity/index.tsx
> +// import Link from "next/link";
This line can be removed

2022-07-15 10:18 UTC, ladytrekker commented on site/components/pages/Infinity/index.tsx
> +                href="https://klima-dao.notion.site/Welcome-to-Klima-Infinity-f2626cb26a474e879287038662e83e47"
Here too

2022-07-15 10:18 UTC, ladytrekker commented on site/components/pages/Infinity/index.tsx
> +                href="https://notionforms.io/forms/klimadao-request-for-collaboration"
Same

2022-07-15 10:18 UTC, ladytrekker commented on site/components/pages/Infinity/cards.ts
> +
Just for clarification: All external links int his file are not KlimaDao related and do not have to moved to constants IMO

2022-07-18 20:06 UTC, Atmosfearful requested changes
Page looks awesome! 🎉 
Code is looking pretty solid too, here are few bigger issues to address now tho-- esp. the text/trans tag order because that affects what translators will see when we merge to staging.

Also:
* [ ] For images that are not transparent, and don't take up a lot of screen space, try converting from png to jpg with `convertio.co` or another tool. That seems to shave ~30% off the file size. But consider that *sometimes* for very large images with gradients or other details, the jpg looks noticeably worse. It's tedious but saves us a ton of bandwidth!
* [ ] related to the above, I see that some pngs have transparent rounded corners. If you can, import the rectangular image as a `jpg`, and apply border radius with css instead

2022-07-19 17:09 UTC, goatsOnDrugs commented on site/components/pages/Infinity/index.tsx
> +            <Trans id="infinity.carousel_info">
updated! I will never make that mistake again lol

2022-07-19 17:10 UTC, goatsOnDrugs commented on site/components/pages/Infinity/index.tsx
> +                  <br />
good point. updated,

2022-07-28 08:03 UTC, ladytrekker commented
Closing in favor of https://github.com/KlimaDAO/klimadao/pull/550

2022-07-28 08:03 UTC, closed without merging