fix bond max calc to check max klima to usdc in wallet instead of klima
KlimaDAO/klimadao pull request #524
Opened 2022-07-05 15:14 UTC by goatsOnDrugs

## Description
the bond max was checking users wallet to calculate the max a user can spend. we need to multiply user klima balance by bond quote to get the right number and we were not.

## Related Ticket

Resolves #<issue-number>

## Checklist

- [ ] Building the site with `npm run build-site` works without errors
- [ ] Building the app with `npm run build-app` works without errors
- [ ] I formatted JS and TS files with running `npm run format-all`

2022-07-05 23:04 UTC, Atmosfearful requested changes
I don't think this is right,

for normal bonds the max is:
1. the max payable allowed by the contract, otherwise
2. all the tokens you have in your wallet

for inverse bonds the max is:
1. remaining capacity in klima, otherwise
2. all the klima you have in your wallet

here you use `bondquote` which is based on the existing user input. when you click "max" it shouldn't care what the existing input value is right?

2022-07-06 15:13 UTC, goatsOnDrugs commented on app/components/views/Bond/index.tsx
> +    console.log("bondQuote", bondState.bondQuote);
fixed

2022-07-11 11:03 UTC, Atmosfearful requested changes

2022-07-15 06:42 UTC, Atmosfearful approved these changes

2022-07-15 06:42 UTC, merged