Block rate fix
KlimaDAO/klimadao pull request #70
Opened 2022-01-11 21:57 UTC by Vienio99

## Description

## Related Ticket

Resolves #31 

## Checklist

- [X] Building the site with `npm run build-site` works without errors
- [X] Building the app with `npm run build-app` works without errors
- [X] I formatted JS and TS files with running `npm run format-all`

2022-01-12 23:02 UTC, kaxline commented
@Atmosfearful @Vienio99 Is there another use for Block Rate besides estimating time to rebase? If not, can't we just get the `endBlock` from the `epoch` and then query the `EstimateTimeInSec` of the `endBlock`?

2022-01-14 16:38 UTC, Atmosfearful commented
> @Atmosfearful @Vienio99 Is there another use for Block Rate besides estimating time to rebase? If not, can't we just get the `endBlock` from the `epoch` and then query the `EstimateTimeInSec` of the `endBlock`?

Good point, we can use this to replace the constant values used in `ESTIMATED_DAILY_REBASES` and perhaps in the bonds as well. Me and @Vienio99 spoke about this on a call and he is gonna look into it.

Recap:
```
// number of blocks per rebase
EPOCH_INTERVAL = 11520;
rebaseRate = EPOCH_INTERVAL * blockRate;
rebasesPerDay = secondsPerDay / rebaseRate;
```

2022-01-17 18:59 UTC, Atmosfearful requested changes
NICE, good call putting it in redux.
Just one quick change

2022-01-17 18:59 UTC, Atmosfearful commented on lib/utils/getEstimatedDailyRebases/index.ts
> +export async function getEstimatedDailyRebases(blockRate: number) {
this has no `await` so it doesn't need to be an `async` function. You can remove it out of the promises array here 
https://github.com/KlimaDAO/klimadao/pull/70/files#diff-b96f585d57b9419336b96f03d5d29b05d4b7d5855d5162ab0d73d2cca3d8afbdR59

And remove the `awaits` where used

2022-01-17 19:01 UTC, Atmosfearful commented
If this has a significant impact on APY I will need to check with coms and policy team before merging

2022-01-17 19:23 UTC, Atmosfearful commented
Closing this PR in favor of #90 I guess I didn't need to, oh well 🤷

2022-01-17 19:23 UTC, closed without merging