[DRAFT] Pledge error handling
KlimaDAO/klimadao pull request #744
Opened 2022-10-17 17:51 UTC by goatsOnDrugs

## Description
Error handling so api will return a message and name so we can show different errors on pledge form and pledge dashboard

## Related Ticket

Resolves #<issue-number>

## Checklist

- [ ] Building the site with `npm run build-site` works without errors
- [ ] Building the app with `npm run build-app` works without errors
- [ ] I formatted JS and TS files with running `npm run format-all`

2022-10-24 18:49 UTC, Atmosfearful requested changes

2022-10-28 18:56 UTC, goatsOnDrugs commented on site/components/pages/Pledge/PledgeForm/index.tsx
> +        console.log("data", data);
sorry, removed

2022-10-28 18:56 UTC, goatsOnDrugs commented on site/components/pages/Pledge/PledgeDashboard/index.tsx
> +      } else {
Ok, that makes sense. Good idea. Implemented.

2022-10-28 18:56 UTC, goatsOnDrugs commented on site/components/pages/Pledge/lib/firebase.ts
> +      "Something went wrong on our end. Please try again in a few minutes"
Copy updated

2022-10-28 18:57 UTC, goatsOnDrugs commented on site/components/pages/Pledge/lib/firebase.ts
> +    e.name = "BadRequest";
updated

2022-10-31 22:10 UTC, merged