Goats/modal error handling
KlimaDAO/klimadao pull request #900
Opened 2023-01-18 17:12 UTC by goatsOnDrugs

## Description
The modal now expects an errors object with "default" and "refused" keys. We can add more errors but the message from the provider will now be logged to the console correctly so people can send us helpful console logs if they have errors connecting

## Related Ticket

Resolves #841 

## Checklist

- [x] I have run `npm run build-all` without errors
- [x] I have formatted JS and TS files with `npm run format-all`

2023-01-25 23:47 UTC, Atmosfearful requested changes

2023-01-25 23:47 UTC, Atmosfearful commented on app/lib/constants.ts
> +    message: "User refused connection. Dont do that. Bad user.",
lol lets be boring
```suggestion
    message: "User refused connection.",
```

2023-01-25 23:47 UTC, Atmosfearful commented on site/lib/constants.ts
> +    message: "User refused connection. Dont do that. Bad user.",
```suggestion
    message: "User refused connection.",
```

2023-01-27 14:06 UTC, goatsOnDrugs commented on app/lib/constants.ts
> +    message: "User refused connection. Dont do that. Bad user.",
updated :)

2023-01-27 23:17 UTC, Atmosfearful approved these changes

2023-01-27 23:17 UTC, merged